name = "olive-r2-upload"
main = "worker-r2.js"
compatibility_date = "2026-09-16"

preview_urls = true

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "olive-storage"

[observability]
enabled = true

[observability.logs]
enabled = true
